### ISSUE TITLE
Browse Page: Get All Products

### ISSUE THREAD

**Issue by mfischercodes** [CMPT362-Useify/Useify-Marketplace#21]
Browse Page

Get All Products from our product database

Parsing the title, price and image from them so that they show on the gridview

should look like this but with data from our database

![image](https://user-images.githubusercontent.com/79065779/180886169-a9ce3a94-8286-4484-a6da-cc4909818ec5.png)

**Comment by yfchen123** [comment]
The push does not work in my android studio so i am going to have to upload the whole folder to github:
<img width="1160" alt="Screen Shot 2022-07-26 at 5 39 03 PM" src="https://user-images.githubusercontent.com/61913966/181135830-402bf3be-cedb-45ed-b53a-1dbd684491d3.png">
And also it does not let me make pull requests so i will just upload the whole folder here: That been said here is the intial commit for the folder: The folder is too large so i will need to make multiple uploads.
